export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const CLEAR_ERRORS = "CLEAR_ERRORS";